routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@getIndex');

Route::get('/about', 'PagesController@getAbout');

Route::get('/contact', 'PagesController@getContact');

Route::get('/{user}/friends',[
  'uses' => 'UserController@showFriends',
  'as' => 'users.showFriends'
]);

Route::post('/searchFriends',[
  'uses' => 'UserController@searchFriends',
  'as' => 'users.searchFriends'
]);

Route::get('/{user}/profile',[
  'uses' => 'UserController@showProfile',
  'as' => 'users.showProfile'
]);

Route::get('/{user}/sendFriendRequest',[
  'uses' => 'UserController@sendFriendRequest',
  'as' => 'users.sendFriendRequest'
]);

Route::get('/{user}/deleteFriends',[
  'uses' => 'UserController@deleteFriends',
  'as' => 'users.deleteFriends'
]);

Route::get('/deletePost/{postid}',[
  'uses' => 'PostController@deletePost',
  'as' => 'posts.deletePost'
]);

Route::post('/addComment/{post}',[
  'uses' => 'PostController@addComment',
  'as' => 'posts.addComment'
]);

Auth::routes();

Route::get('/more', 'PagesController@getMore');

Route::resource('users' , 'UserController');

Route::resource('posts' , 'PostController');

resources/views/partials/postLayout.blade.php
        <div class="panel panel-success">
          <div class="panel-heading">
            <div class="panel-title">
                    <div class="row">
                            <div class="col-md-7">
                                    {{$post->title}}
                            </div>

                            <div class="col-md-offset-1 col-md-4">
                                   <small><a class="text-right" href="{{route('users.showProfile',$post->user_id)}}">{{$post->name .' '. $post->last_name}}</a></small>
                           </div>
                    </div>


            </div>

         </div>
          <div class="panel-body">
              {{$post->body}}



</div>
<div class="panel-body">
          <nav class="navbar-right" style="margin:auto">
                  <button type="button" class="btn btn-default btn-xs addComment" >
                          <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Szybka Odpowiedź
                </button>
                        <a href="{{route('posts.show',$post->post_id)}}">
                                <button type="button" class="btn btn-default btn-xs">
                                        <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Przejdź do postu
                                </button>
                        </a>
                    <a href="#">
                            <button type="button" class="btn btn-default btn-xs">
                                    <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Poka komenty
                            </button>
                    </a>
                    @if($post->user_id==Auth::user()->id)
                      <a href="{{route('posts.deletePost', $post->post_id)}}">
                            <button type="button" class="btn btn-default btn-xs">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Usun post
                            </button>
                      </a>
                    @endif
          </nav>
 </div>
                <div class="panel-footer post-footer" >
                        <form class="form-group form-inline" action="{{ route('posts.addComment',$post->post_id) }}" method="post">
                                  {{ csrf_field() }}
                                  <label for="comment_body" class="sr-only"></label>
                          <textarea class="form-control input-sm" id="comment_body" name="comment_body" cols='70' placeholder="Wpisz komentarz..." style="height:auto";></textarea>
                         <button type="submit" name="button" class="btn btn-success btn-xs">Dodaj</button>

                  </form>

                </div>
        </div>

resources/views/partials/userScreen.blade.php
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Dodaj post</h4>
      </div>
      <div class="modal-body">

          <form class="form" action="{{ route('posts.store') }}" method="POST">
            {{ csrf_field() }}
          <div class="form-group" role="form">
            <label for="Title"></label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Wpisz tytuł posta">

            <hr>

            <textarea class="form-control" name="body" rows="8" cols="60" placeholder="Wpisz treść posta"></textarea>

          </div>
          <p class="text-right">
            <button type="submit" name="button" class="btn btn-success">Stwórz posta</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
        </p>


          </form>

      </div>
    </div>
  </div>
</div>
<!--Koniec modala-->

<div class="container">
  <div class="row">
            <div class="col-md-2">
            <!--    <a href="#" class="thumbnail"> -->
              <img src="" alt="{{Auth::user()->name}}" style="height:180px;width:172px;">
            <!--     </a>-->  {{Auth::user()->getFullName()}}<br />
                              {{Auth::user()->city}}<br>
                              user id : {{Auth::user()->id}}

            </div>





            <div class="col-md-7" style="height:100px;">
              
                  @foreach($posts as $post)

                  @include('partials.postLayout')
                  @endforeach
            <div class="col-md-3">

            </div>
  </div>
  <div class="row">
    <div class="col-md-2 panel-body">
          <a href="" role="button" data-toggle="modal" data-target="#myModal" class="btn btn-primary"><i class="fa fa-btn fa-plus"></i> Dodaj post</a>
    </div>
  </div>

</div>