routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@getIndex');

Route::get('/about', 'PagesController@getAbout');

Route::get('/contact', 'PagesController@getContact');

Route::get('/{user}/friends',[
  'uses' => 'UserController@showFriends',
  'as' => 'users.showFriends'
]);

Route::post('/searchFriends',[
  'uses' => 'UserController@searchFriends',
  'as' => 'users.searchFriends'
]);

Route::get('/{user}/profile',[
  'uses' => 'UserController@showProfile',
  'as' => 'users.showProfile'
]);

Route::get('/{user}/sendFriendRequest',[
  'uses' => 'UserController@sendFriendRequest',
  'as' => 'users.sendFriendRequest'
]);

Route::get('/{user}/deleteFriends',[
  'uses' => 'UserController@deleteFriends',
  'as' => 'users.deleteFriends'
]);

Route::get('/deletePost/{postid}',[
  'uses' => 'PostController@deletePost',
  'as' => 'posts.deletePost'
]);

Route::post('/addComment/{post}',[
  'uses' => 'PostController@addComment',
  'as' => 'posts.addComment'
]);

Auth::routes();

Route::get('/more', 'PagesController@getMore');

Route::resource('users' , 'UserController');

Route::resource('posts' , 'PostController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Lifters') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font-awesome.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Scripts -->



    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
@yield('head')



</head>
<body>
    <div id="app">
        <nav class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                          <img alt="Lifters" src="/uploads/logo/logo.png" style="position:relative;top:-23px;">
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        @if (Auth::guest())
                        <li><a href="/about">O nas</a></li>
                        <li><a href="/contact">Kontakt</a></li>
                        &nbsp;
                        @else
                        <form class="navbar-form navbar-left" action="{{route('users.searchFriends')}}" method="POST">
                            <div class="form-group">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <input type="text" class="form-control" name="field" placeholder="Wyszukaj osobę...">
                            </div>
                                <button type="submit" class="btn btn-default"><i class="fa fa-btn fa-search"></i> Szukaj</button>
                        </form>
                        @endif
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Zaloguj</a></li>
                            <li><a href="{{ route('register') }}">Zarejestruj</a></li>
                        @else
                            <li><a href="{{route('users.showFriends',Auth::user())}}"><i class="fa fa-btn fa-users"></i> Znajomi</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" role="menu">
                                  <li>
                                      <a href="{{route('users.edit',Auth::user()->id)}}">
                                            <i class="fa fa-btn fa-user"></i>  Twój profil
                                      </a>
                                  </li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                          <i class="fa fa-btn fa-sign-out"></i>  Wyloguj
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav><!-- Koniec navbara -->


            <div class="container">
                    @yield('content')
            </div>

    </div>

    <!-- Scripts -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/myjquery.js') }}"></script>

@yield('scripts')
</body>
</html>